"use client";

import { useState, type ReactNode } from "react";
import Link from "next/link";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import toast from "react-hot-toast";
import { EvidenceStudio, InterviewStudio, PreferencesForm, type DiscoveryPreferences, type EvidenceEntry } from "@/components/career/EvidenceStudio";

type Evidence = EvidenceEntry;
type Draft = { kind?: string; subjects?: string[]; id: string; title: string; subject: string; body: string; recipient: string | null; reviewedAt: string | null; evidence: Array<{ evidenceId: string; quote: string; source: string }>; versions: Array<{ subject: string; body: string; savedAt: string }> };
type Overview = { preference?: { preferences: DiscoveryPreferences }; evidence: Evidence[]; documents: Draft[]; jobs: Array<{ id: string; title: string; company: string }>; resumes: Array<{ id: string; title: string; version: number }>; plan: string; limits: Record<string, number | null>; usage: Array<{ feature: string; used: number }>; outcomes: Record<string, number>; resetAt: string };
type Analysis = { result: { score: number | null; disclaimer: string; method: string; risks: string[]; requirements: Array<{ requirement: string; status: string; citation: { source: string; quote: string } | null }>; breakdown: Record<string, string | number | null> } };
type Source = { id: string; company: string; provider: string };
const fieldClass = "w-full rounded-xl border border-violet-500/20 bg-background p-3 text-sm outline-none focus:ring-2 focus:ring-violet-500";
const tabs = ["Evidence", "Discover", "Alignment", "Email studio", "Interview", "Connections", "Insights"] as const;

export default function CareerPage() {
  const client = useQueryClient();
  const query = useQuery({ queryKey: ["career"], queryFn: () => api.get<Overview>("/career") });
  const [tab, setTab] = useState<(typeof tabs)[number]>("Evidence");
  const [busy, setBusy] = useState(false);
  const [jobId, setJobId] = useState(""); const [resumeId, setResumeId] = useState("");
  const [selected, setSelected] = useState<string[]>([]);
  const [analysisDocumentId, setAnalysisDocumentId] = useState("");
  const [combined, setCombined] = useState(false);
  const [analysis, setAnalysis] = useState<Analysis | null>(null);
  const [draft, setDraft] = useState<Draft | null>(null);
  const [preview, setPreview] = useState<{ previewKey: string; before: { summary?: string }; after: { summary: string } } | null>(null);
  const [kind, setKind] = useState("APPLICATION"); const [tone, setTone] = useState("neutral"); const [length, setLength] = useState("standard");
  async function run(fn: () => Promise<void>) {
    setBusy(true); try { await fn(); await client.invalidateQueries({ queryKey: ["career"] }); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not complete the action."); } finally { setBusy(false); }
  }
  if (query.isPending) return <p className="p-8" role="status">Loading your career workspace…</p>;
  if (query.isError || !query.data) return <div className="p-8"><p role="alert">{query.error?.message ?? "Workspace unavailable"}</p><Button onClick={() => query.refetch()}>Retry</Button></div>;
  const data = query.data;
  const context = <div className="grid gap-4 sm:grid-cols-2"><Field label="Job"><select className={fieldClass} value={jobId} onChange={e => { setJobId(e.target.value); setAnalysis(null); setPreview(null); }}><option value="">Choose a saved job</option>{data.jobs.map(j => <option key={j.id} value={j.id}>{j.title} · {j.company}</option>)}</select></Field><Field label="Resume"><select className={fieldClass} value={resumeId} onChange={e => { setResumeId(e.target.value); setAnalysis(null); setPreview(null); }}><option value="">Choose a resume</option>{data.resumes.map(r => <option key={r.id} value={r.id}>{r.title} · v{r.version}</option>)}</select></Field></div>;
  const claims = <fieldset className="space-y-3"><legend className="mb-2 font-medium">Confirmed achievements to use</legend>{data.evidence.filter(e => ["VERIFIED", "USER_CONFIRMED"].includes(e.status)).map(e => <label key={e.id} className="flex items-start gap-3 rounded-xl border p-3"><input type="checkbox" className="mt-1" checked={selected.includes(e.id)} onChange={ev => { setSelected(ev.target.checked ? [...selected, e.id] : selected.filter(id => id !== e.id)); setPreview(null); }} /><span>{e.title}<span className="block text-sm text-muted-foreground">{e.statement}</span></span></label>)}{!data.evidence.length && <p className="text-sm text-muted-foreground">Add a confirmed achievement in Evidence first. Metrics are optional.</p>}</fieldset>;
  return <div className="mx-auto max-w-6xl space-y-6 px-4 pb-12 lg:px-6">
    <header className="rounded-3xl bg-gradient-to-br from-[#170a31] to-[#42166b] p-7 text-white"><p className="text-sm text-violet-200">Your career memory</p><h1 className="mt-2 text-3xl font-semibold">Build an application you can stand behind.</h1><p className="mt-3 max-w-2xl text-violet-100">Connect real evidence to a role, review your documents, and keep control of every send.</p><Link href="/dashboard/jobs" className="mt-4 inline-block underline underline-offset-4">Open job workspace</Link></header>
    <nav aria-label="Career workspace sections" className="flex flex-wrap gap-2">{tabs.map(t => <Button key={t} variant={t === tab ? "default" : "outline"} aria-pressed={t === tab} onClick={() => setTab(t)}>{t}</Button>)}</nav>
    <div className="flex flex-wrap gap-3 text-sm text-muted-foreground"><span className="capitalize">{data.plan} plan</span>{["alignment", "draft", "tailor", "interview", "recommendations"].map(f => <span key={f}>{f}{f === "recommendations" ? " (weekly)" : ""}: {data.usage.find(u => u.feature === f)?.used ?? 0}/{data.limits[f]}</span>)}<span>Resets {new Date(data.resetAt).toLocaleDateString()}</span></div>
    {tab === "Evidence" && <EvidenceStudio evidence={data.evidence} busy={busy} run={run} onDelete={id => { setSelected(selected.filter(value => value !== id)); setPreview(null); }} />}
    {tab === "Interview" && <InterviewStudio evidence={data.evidence} documents={data.documents} plan={data.plan} busy={busy} run={run} />}
    {tab === "Discover" && <Discovery run={run} busy={busy} preferences={data.preference?.preferences} />}
    {tab === "Alignment" && <Panel title="Job alignment & resume review">{context}<Field label="Document to analyze"><select className={fieldClass} value={analysisDocumentId} onChange={e => setAnalysisDocumentId(e.target.value)}><option value="">Resume only</option>{data.documents.filter(d => d.kind !== "INTERVIEW_STORY").map(d => <option key={d.id} value={d.id}>{d.title}</option>)}</select></Field>{analysisDocumentId && <label className="flex items-center gap-3"><input type="checkbox" checked={combined} onChange={e => setCombined(e.target.checked)} />Include resume for combined readiness</label>}<Button disabled={busy || !jobId || !resumeId} onClick={() => void run(async () => setAnalysis(await api.post<Analysis>("/career/alignment", { jobId, resumeId, ...(analysisDocumentId ? { documentId: analysisDocumentId, combined } : {}) })))}>Analyze alignment</Button>{analysis && <div className="space-y-4"><h3 className="text-xl">Evidence coverage: {analysis.result.score ?? "Not enough information"}{analysis.result.score !== null && "%"}</h3><p className="text-sm text-muted-foreground">{analysis.result.disclaimer}</p>{analysis.result.risks.map(r => <p key={r} className="rounded-xl border border-amber-500/30 p-3 text-sm">{r}</p>)}<dl className="grid gap-3 sm:grid-cols-2">{Object.entries(analysis.result.breakdown).map(([k, v]) => <div key={k} className="rounded-xl border p-3"><dt className="text-sm font-medium">{k.replace(/([A-Z])/g, " $1")}</dt><dd className="text-sm text-muted-foreground">{v ?? "Needs review"}</dd></div>)}</dl>{analysis.result.requirements.map((r, i) => <article key={i} className="rounded-xl border p-4"><p className="text-xs font-semibold uppercase text-violet-600 dark:text-violet-300">{r.status}</p><p className="my-2">{r.requirement}</p>{r.citation && <blockquote className="border-l-2 border-violet-400 pl-3 text-sm text-muted-foreground">{r.citation.quote}<cite className="block">{r.citation.source}</cite></blockquote>}</article>)}</div>}{claims}<Button variant="outline" disabled={busy || !jobId || !resumeId || !selected.length} onClick={() => void run(async () => setPreview(await api.post("/career/tailor", { jobId, resumeId, evidenceIds: selected, accept: false })))}>Preview tailored summary</Button>{preview && <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><div><h3>Before</h3><p className="text-sm">{preview.before.summary ?? "No summary"}</p></div><div><h3>After</h3><p className="text-sm">{preview.after.summary}</p></div></div><Button disabled={busy} onClick={() => void run(async () => { await api.post("/career/tailor", { jobId, resumeId, evidenceIds: selected, accept: true, previewKey: preview.previewKey }); setPreview(null); toast.success("Saved as a new resume version"); })}>Accept and save new version</Button></div>}</Panel>}
    {tab === "Email studio" && <div className="grid gap-6 lg:grid-cols-2"><Panel title="Compose a grounded draft">{context}{claims}<Field label="Message purpose"><select value={kind} onChange={e => setKind(e.target.value)} className={fieldClass}>{["APPLICATION", "OUTREACH", "FOLLOW_UP", "THANK_YOU", "REFERRAL", "COVER_LETTER"].map(k => <option key={k}>{k}</option>)}</select></Field><div className="grid grid-cols-2 gap-3"><Field label="Tone"><select className={fieldClass} value={tone} onChange={e => setTone(e.target.value)}><option value="neutral">Neutral</option><option value="warm">Warmer</option><option value="confident">More confident</option></select></Field><Field label="Length"><select className={fieldClass} value={length} onChange={e => setLength(e.target.value)}><option value="standard">Standard</option><option value="short">Shorter</option></select></Field></div><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={busy} onClick={() => void run(async () => { await api.put("/career/style", { tone, length }); toast.success("Writing preferences saved"); })}>Remember this tone and length</Button>{data.preference?.preferences.writingStyle && <Button variant="outline" onClick={() => { const style = data.preference!.preferences.writingStyle!; setTone(style.tone); setLength(style.length); }}>Use my saved style</Button>}</div><Button disabled={busy || !jobId} onClick={() => void run(async () => setDraft(await api.post<Draft>("/career/drafts", { jobId, ...(resumeId ? { resumeId } : {}), evidenceIds: selected, kind, tone, length })))}>Create draft</Button><h3 className="font-medium">Saved drafts</h3>{data.documents.filter(d => d.kind !== "INTERVIEW_STORY").map(d => <button key={d.id} className="block w-full rounded-xl border p-3 text-left text-sm hover:bg-violet-500/5" onClick={() => setDraft(d)}>{d.title}</button>)}</Panel>
      <Panel title="Review before sending">{!draft ? <p>Create or open a draft to edit it.</p> : <><Field label="Recipient email"><input type="email" className={fieldClass} value={draft.recipient ?? ""} onChange={e => setDraft({ ...draft, recipient: e.target.value, reviewedAt: null })} /></Field><div className="flex flex-wrap gap-2">{draft.subjects?.map(subject => <Button key={subject} variant="outline" onClick={() => setDraft({ ...draft, subject, reviewedAt: null })}>{subject}</Button>)}</div><Field label="Subject"><input className={fieldClass} value={draft.subject} onChange={e => setDraft({ ...draft, subject: e.target.value, reviewedAt: null })} /></Field><Field label="Draft"><textarea className={fieldClass} rows={14} value={draft.body} onChange={e => setDraft({ ...draft, body: e.target.value, reviewedAt: null })} /></Field><p className="text-sm text-muted-foreground">Review every claim, recipient and attachment before sending. Attachments are not sent from this studio.</p><Button disabled={busy} onClick={() => void run(async () => setDraft(await api.put<Draft>(`/career/drafts/${draft.id}`, { subject: draft.subject, body: draft.body, ...(draft.recipient ? { recipient: draft.recipient } : {}), reviewed: true })))}>Save reviewed draft</Button><Button variant="outline" disabled={busy || !draft.reviewedAt || !draft.recipient} onClick={() => void run(async () => { await api.post(`/career/drafts/${draft.id}/send`, { key: crypto.randomUUID(), reviewed: true }); toast.success("Queued. Check Connections for delivery status."); })}>Send reviewed email</Button><details><summary className="cursor-pointer">Claim sources & draft history</summary>{draft.evidence.map((e, i) => <p key={i} className="mt-3 text-sm">{e.quote} — {e.source}</p>)}{draft.versions.map((v, i) => <article key={i} className="mt-3 whitespace-pre-wrap border-t pt-3 text-sm"><time>{new Date(v.savedAt).toLocaleString()}</time><p>{v.body}</p></article>)}</details><Button variant="ghost" disabled={busy} onClick={() => void run(async () => { await api.delete(`/career/drafts/${draft.id}`); setDraft(null); })}>Delete draft</Button></>}</Panel></div>}
    {tab === "Connections" && <Connections run={run} busy={busy} />}
    {tab === "Insights" && <Panel title="Your outcomes, not predictions"><div className="grid gap-4 sm:grid-cols-3">{Object.entries(data.outcomes).map(([status, count]) => <div key={status} className="rounded-xl border p-4"><p className="text-3xl">{count}</p><p className="text-sm">{status.replaceAll("_", " ")}</p></div>)}</div><p className="text-sm text-muted-foreground">These are your recorded application states. Small samples cannot establish what caused an outcome. Alignment and evidence-based drafts use local rules and have no AI-provider token cost.</p><Button variant="outline" onClick={() => void run(async () => { const value = await api.get("/career/export"); const url = URL.createObjectURL(new Blob([JSON.stringify(value, null, 2)], { type: "application/json" })); const a = document.createElement("a"); a.href = url; a.download = "profileai-export.json"; a.click(); URL.revokeObjectURL(url); })}>Export my workspace data</Button><Link className="block underline" href="/dashboard/settings">Account privacy and deletion settings</Link></Panel>}
  </div>;
}
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block space-y-2 text-sm"><span>{label}</span>{children}</label>; }
function Panel({ title, children }: { title: string; children: ReactNode }) { return <Card className="space-y-5 border-violet-500/15 p-5 sm:p-6"><h2 className="text-xl font-semibold">{title}</h2>{children}</Card>; }
type Actions = { run: (fn: () => Promise<void>) => Promise<void>; busy: boolean };
function Discovery({ run, busy, preferences }: Actions & { preferences?: DiscoveryPreferences }) {
  const sources = useQuery({ queryKey: ["career", "sources"], queryFn: () => api.get<Source[]>("/career/sources") });
  const [source, setSource] = useState("");
  const [jobs, setJobs] = useState<Array<{ externalId: string; title: string; company: string; description: string; canonicalUrl: string; why: string[]; uncertainty: string }>>([]);
  return <Panel title="Discover from approved sources"><PreferencesForm preferences={preferences} run={run} busy={busy} /><Field label="Company source"><select value={source} onChange={e => { setSource(e.target.value); setJobs([]); }} className={fieldClass}><option value="">Select an approved source</option>{sources.data?.map(s => <option key={s.id} value={s.id}>{s.company} · {s.provider}</option>)}</select></Field>{sources.data?.length === 0 && <p>No approved sources yet. You can still <Link href="/dashboard/jobs" className="underline">import a job privately</Link>.</p>}<Button disabled={busy || !source} onClick={() => void run(async () => { const result = await api.get<{ jobs: typeof jobs }>(`/career/sources/${source}/jobs`); setJobs(result.jobs); })}>Discover jobs</Button>{jobs.map(j => <article key={j.externalId} className="space-y-3 rounded-xl border p-4"><h3 className="font-medium">{j.title} · {j.company}</h3><p className="line-clamp-4 text-sm text-muted-foreground">{j.description}</p><p className="text-sm text-violet-600 dark:text-violet-300">{j.why.join(" · ") || "Explore this role against your evidence"}</p><p className="text-xs text-muted-foreground">{j.uncertainty}</p><a className="text-sm underline" href={j.canonicalUrl} target="_blank" rel="noreferrer">Original listing</a><Button className="ml-3" variant="outline" disabled={busy} onClick={() => void run(async () => { await api.post(`/career/sources/${source}/import`, { externalId: j.externalId }); toast.success("Saved to job workspace"); })}>Save job</Button></article>)}</Panel>;
}
function Connections({ run, busy }: Actions) {
  const q = useQuery({ queryKey: ["career", "connections"], queryFn: () => api.get<{ configured: boolean; connections: Array<{ provider: string }>; deliveries: Array<{ id: string; kind: string; state: string; error: string | null }> }>("/career/integrations"), refetchInterval: 30000 });
  return <Panel title="Email & calendar connections"><p className="text-sm text-muted-foreground">Google consent grants sending or calendar-event access only. Tokens are encrypted. No mailbox password is collected.</p>{q.data?.configured === false && <p>The administrator must configure Google OAuth before connections are available.</p>}{(["mail", "calendar"] as const).map(p => <div key={p} className="flex items-center gap-4"><span className="min-w-32">Google {p}</span>{q.data?.connections.some(c => c.provider === `google-${p}`) ? <Button variant="outline" disabled={busy} onClick={() => void run(async () => { await api.post("/career/integrations/disconnect", { purpose: p }); })}>Disconnect</Button> : <Button disabled={busy || !q.data?.configured} onClick={() => void run(async () => { const result = await api.post<{ url: string }>("/career/integrations/connect", { purpose: p }); window.location.assign(result.url); })}>Connect</Button>}</div>)}<form className="space-y-3" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void run(async () => { await api.post("/career/calendar", { key: crypto.randomUUID(), summary: f.get("summary"), start: new Date(String(f.get("start"))).toISOString(), end: new Date(String(f.get("end"))).toISOString(), reviewed: true }); toast.success("Reviewed event queued"); }); }}><h3 className="font-medium">Review a calendar event</h3><Field label="Interview or follow-up title"><input name="summary" required className={fieldClass} /></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Start (your local time)"><input type="datetime-local" name="start" required className={fieldClass} /></Field><Field label="End (your local time)"><input type="datetime-local" name="end" required className={fieldClass} /></Field></div><Button disabled={busy || !q.data?.connections.some(c => c.provider === "google-calendar")} type="submit">Create reviewed event</Button></form><h3 className="font-medium">Delivery status</h3>{q.data?.deliveries.map(d => <div key={d.id} className="rounded-xl border p-3 text-sm">{d.kind} · {d.state}{d.error && <p className="mt-1 text-muted-foreground">{d.error}</p>}</div>)}</Panel>;
}
