"use client";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { api } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import toast from "react-hot-toast";
export default function SourcesPage() {
  const q = useQuery({ queryKey: ["source-health"], queryFn: () => api.get<Array<{ id: string; company: string; provider: string; board: string; failures: number; enabled: boolean; lastError: string | null }>>("/career/admin/sources") });
  const [busy, setBusy] = useState(false);
  return <div className="mx-auto max-w-4xl space-y-6 p-6"><h1 className="text-3xl font-semibold">Source policy & health</h1><p>Approve only boards whose access and storage policy you have reviewed. Three consecutive failures pause a source.</p>{q.isError && <p role="alert">{q.error.message}</p>}<Card className="p-5"><form className="grid gap-4 sm:grid-cols-2" onSubmit={async e => { e.preventDefault(); const f = new FormData(e.currentTarget); setBusy(true); try { await api.post("/career/admin/sources", { provider: f.get("provider"), board: f.get("board"), company: f.get("company"), enabled: f.get("enabled") === "on", policy: { accessMethod: "PUBLIC_API", storageAllowed: f.get("storage") === "on", republicationAllowed: f.get("republication") === "on", indexingAllowed: f.get("indexing") === "on", retentionDays: Number(f.get("retention")), attribution: f.get("attribution"), display: f.get("display"), reviewedAt: new Date().toISOString(), reference: f.get("reference") } }); await q.refetch(); toast.success("Policy saved"); } catch (error) { toast.error(error instanceof Error ? error.message : "Save failed"); } finally { setBusy(false); } }}>
    <label>Provider<select name="provider" className="mt-2 w-full rounded-lg border bg-background p-3"><option>LEVER</option><option>GREENHOUSE</option></select></label>{[["board", "Board identifier"], ["company", "Company"], ["attribution", "Attribution"], ["reference", "Policy reference URL"]].map(([name, label]) => <label key={name}>{label}<input required name={name} type={name === "reference" ? "url" : "text"} className="mt-2 w-full rounded-lg border p-3" /></label>)}<label>Display mode<select name="display" className="mt-2 w-full rounded-lg border bg-background p-3"><option value="LINK_ONLY">Private link only</option><option value="SUMMARY">Attributed summary</option><option value="FULL">Full description</option></select></label><label>Retention days<input name="retention" type="number" min={1} max={90} defaultValue={30} className="mt-2 w-full rounded-lg border p-3" /></label>{[["storage", "Storage permitted"], ["republication", "Republication permitted"], ["indexing", "Indexing permitted"], ["enabled", "Enable reviewed source"]].map(([name, label]) => <label key={name} className="flex items-center gap-3"><input name={name} type="checkbox" />{label}</label>)}<Button disabled={busy} type="submit">Save reviewed policy</Button></form></Card>{q.data?.map(s => <Card key={s.id} className="p-5"><h2 className="font-semibold">{s.company} · {s.provider} / {s.board}</h2><p>{s.enabled ? "Enabled" : "Paused"} · {s.failures} consecutive failures</p>{s.lastError && <p className="text-sm text-muted-foreground">{s.lastError}</p>}</Card>)}</div>;
}
