"use client";
import { useState, type ReactNode } from "react";
import Link from "next/link";
import { motion, useReducedMotion } from "framer-motion";
import { ArrowUpRight, CheckCircle2, CircleHelp, CircleDashed, Sparkles, LockKeyhole, Fingerprint, FileCheck2, CalendarClock } from "lucide-react";

export function ProductDisplay({ children }: { children: ReactNode }) {
  return <div className="career-display">{children}</div>;
}
export function CareerJourneyDemo({ section }: { section: "match" | "workspace" | "readiness" | "email" | "privacy" }) {
  const reduced = useReducedMotion();
  const [showEvidence, setShowEvidence] = useState(true);
  const [warm, setWarm] = useState(false);
  if (section === "privacy") return <section id="privacy-control" className="career-section-wide"><div className="career-section-inner"><div className="career-wide-heading" data-aos="fade-up"><div><span className="career-demo-label">BUILT AROUND YOUR CONTROL</span><h2>Your next chapter.<br />Your private space.</h2></div><p>Thoughtful defaults for the documents, decisions and details that matter.</p></div><div className="career-privacy-grid">{[[LockKeyhole,"Private by default","Imported roles, personal evidence and drafts stay in your workspace."],[Fingerprint,"Trace every claim","See the evidence behind a statement. Keep unsupported details out."],[FileCheck2,"You have the final say","Edit every draft, review every send, export your data or disconnect your accounts."]].map(([Icon,title,text]) => { const Symbol = Icon as typeof LockKeyhole; return <article key={String(title)} data-aos="fade-up"><Symbol size={28} /><h3>{String(title)}</h3><p>{String(text)}</p></article>; })}</div><div className="career-allowances"><table><caption>Career Studio monthly allowances · transparent from day one</caption><thead><tr>{["Capability","Free","Pro","Career Plus"].map(t => <th key={t}>{t}</th>)}</tr></thead><tbody>{[["Alignment analyses","3","50","150"],["Tailored summaries","2","20","60"],["Application drafts","5","50","150"]].map(row => <tr key={row[0]}>{row.map((t,i) => <td key={i}>{t}</td>)}</tr>)}</tbody></table></div></div></section>;
  const copy = {
    match: ["01 / OPPORTUNITY, WITH CONTEXT", "A good match deserves a clear explanation.", "Go beyond a job title. See where your experience connects, where a claim needs evidence, and what to review before applying."],
    workspace: ["02 / A PLACE FOR EVERY POSSIBILITY", "Less scattered. More in motion.", "Keep the role, your documents, application progress and the next action together. One calm workspace from saved job to final decision."],
    readiness: ["03 / YOUR EXPERIENCE, IN FOCUS", "Make the real work shine.", "Turn a vague summary into a clear account of your contribution. Review the before and after, then save the version you believe in."],
    email: ["04 / A LITTLE MORE HUMAN", "Sound like yourself. On a really good day.", "Bring your confirmed achievements into a focused, editable draft. Adjust the tone, find a natural opening, and make every word yours."],
  }[section];
  return <section id={section} className={`career-demo ${section === "workspace" || section === "email" ? "reverse" : ""}`}><div className="career-demo-shell">
    <div className="career-demo-copy" data-aos="fade-up"><span className="career-demo-label">{copy[0]}</span><h2>{copy[1]}</h2><p className="career-demo-lede">{copy[2]}</p><Link className="career-demo-action" href={section === "workspace" ? "/dashboard/jobs" : "/dashboard/career"}>Explore {section === "workspace" ? "your job workspace" : "Career Studio"} <ArrowUpRight size={16}/></Link><p className="career-demo-note">{section === "match" ? "Alignment is evidence coverage, never a hiring probability." : "Illustrative product preview. Your real experience comes first."}</p></div>
    <div data-aos="fade-up"><ProductDisplay><div className="career-display-heading"><span><i />{section === "email" ? "APPLICATION DRAFT" : section === "workspace" ? "YOUR APPLICATIONS" : section === "readiness" ? "REVIEW CHANGES" : "JOB ALIGNMENT"}</span><span>DEMO</span></div>
      {section === "match" && <><div className="career-demo-job"><h3>Frontend Engineer</h3><p>Example Studio · Product team</p><div className="career-demo-tags"><span className="career-tag">Remote</span><span className="career-tag">React</span><span className="career-tag">Design systems</span></div></div><button className="career-inline-button" aria-expanded={showEvidence} onClick={() => setShowEvidence(!showEvidence)}><Sparkles size={14}/>{showEvidence ? "Hide evidence" : "Why this role?"}</button><motion.div className="career-evidence-map" initial={false} animate={{opacity:showEvidence?1:0, x:showEvidence?0:10}} transition={{duration:reduced?0:.28}} aria-hidden={!showEvidence}><svg className="career-evidence-wire" viewBox="0 0 200 300" preserveAspectRatio="none" aria-hidden="true"><path d="M 0 170 C 100 170 90 50 200 50"/><circle cx="196" cy="50" r="3"/></svg><div className="career-evidence-row"><CheckCircle2 size={16}/><div><b>STRONG EVIDENCE</b><p>React appears in your confirmed dashboard project.</p></div></div><div className="career-evidence-row"><CircleHelp size={16}/><div><b>NEEDS CONTEXT</b><p>The role includes mentoring. Add a specific example.</p></div></div><div className="career-evidence-row"><CircleDashed size={16}/><div><b>NOT YET EVIDENCED</b><p>No accessibility testing evidence has been added.</p></div></div></motion.div></>}
      {section === "workspace" && <><div className="career-workspace-address"><span>◎ &nbsp; Your workspace</span><span>Applications &nbsp; / &nbsp; Board view</span><span>AM</span></div><div className="career-pipeline">{["Preparing","Applied","Interview"].map((state,i) => <div className="career-pipeline-column" key={state}><span>{state} · {i === 0 ? "2" : "1"}</span><div className={`career-mini-job ${i === 2 ? "highlighted" : ""}`}>{["Frontend Engineer","Product Engineer","UI Engineer"][i]}<small>Example company</small><span className="career-tag mt-3">{["Review resume","Awaiting reply","Prepare stories"][i]}</span></div>{i === 0 && <div className="career-mini-job">Design Engineer<small>Example Studio</small></div>}</div>)}</div><div className="career-next-action"><CalendarClock size={16}/><div>One next step, always in sight.<br /><span className="text-xs opacity-60">Review the role before preparing your application.</span></div></div></>}
      {section === "readiness" && <div className="career-comparison mt-5"><div><small>BEFORE · TOO VAGUE</small><p>Worked on frontend tasks.</p></div><div className="career-after"><small>AFTER · CONFIRM BEFORE ACCEPTING</small><p>Built reusable React components for the customer dashboard.</p><div className="career-demo-tags"><span className="career-tag">Specific contribution</span><span className="career-tag">No invented metrics</span></div></div><div className="career-display-footer"><span>Changes remain yours to accept.</span><FileCheck2 size={17}/></div></div>}
      {section === "email" && <><div className="career-email-subject">Subject: Frontend Engineer — application</div><div className="career-email"><p>Hello hiring team,</p><p>I am applying for the Frontend Engineer role. I built reusable React components for a customer dashboard.</p><p>{warm ? "I would welcome the chance to connect. Thank you for considering my note." : "Thank you for your consideration."}</p></div><div className="career-display-footer"><button className="career-inline-button" aria-pressed={warm} onClick={() => setWarm(!warm)}><Sparkles size={13}/>{warm ? "Use neutral tone" : "Make it warmer"}</button><span>Draft only · never auto-sent</span></div></>}
    </ProductDisplay></div>
  </div></section>;
}
