"use client";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { useState } from "react";
import Link from "next/link";
import { ArrowUpRight, CheckCircle2, Fingerprint, Quote, CalendarClock, Bell } from "lucide-react";
import { ProductDisplay } from "./CareerJourneyDemo";

export function CareerExperience({ section }: { section: "evidence" | "interview" | "followup" }) {
  const [step, setStep] = useState(0);
  const reduced = useReducedMotion();
  const stories = ["Our team was building a customer dashboard with repeated interface patterns.", "My responsibility was to make those patterns reusable across the product.", "I built shared React components and documented how the team could use them.", "The team could use one shared component library. Add a measured outcome only if you can confirm it."];
  if (section === "evidence") return <section id="evidence" className="career-section-wide"><div className="career-section-inner"><div className="career-wide-heading"><div><span className="career-demo-label">YOUR EXPERIENCE IS THE SOURCE OF TRUTH</span><h2>Every strong story<br />starts with something real.</h2></div><p>A growing collection of the projects, actions and results you can stand behind.</p></div><div className="career-proof-grid"><ProductDisplay><div className="career-display-heading"><span><Fingerprint size={15}/> EVIDENCE / 001</span><span>EXAMPLE</span></div><div className="career-demo-job"><h3>Customer dashboard</h3><p>Frontend development · React</p></div><Quote size={26} className="text-violet-300"/><p className="career-story mt-3">Built reusable React components and documented how the product team could use them.</p><div className="career-source-stamp"><span>Source: project notes</span><span className="flex items-center gap-2"><CheckCircle2 size={13}/> User confirmed</span></div></ProductDisplay><div><div className="career-proof-note"><CheckCircle2 size={20}/><div><h3>Clear provenance</h3><p>Connect each claim to a source you can explain: a project, portfolio, document or your own account.</p></div></div><div className="career-proof-note"><Fingerprint size={20}/><div><h3>Nothing made up</h3><p>Inferred achievements stay out of generated drafts. A missing number is a question, not a reason to invent one.</p></div></div><Link href="/dashboard/career" className="career-demo-action">Build your Evidence Bank <ArrowUpRight size={16}/></Link></div></div></div></section>;
  return <section id={section} className={`career-demo ${section === "followup" ? "reverse" : ""}`}><div className="career-demo-shell"><div className="career-demo-copy"><span className="career-demo-label">{section === "interview" ? "READY FOR THE CONVERSATION" : "MOMENTUM, WITHOUT THE MENTAL LOAD"}</span><h2>{section === "interview" ? <>You did the work.<br />Now tell the story.</> : <>A thoughtful follow-up.<br />At the right moment.</>}</h2><p className="career-demo-lede">{section === "interview" ? "Use your real projects to prepare a clear Situation, Task, Action and Result. Find the story before you are asked to tell it." : "Bring notes, follow-up reminders and interview plans into one place. Review calendar events before they leave your workspace."}</p><Link className="career-demo-action" href={section === "interview" ? "/dashboard/career" : "/dashboard/applications"}>{section === "interview" ? "Prepare your stories" : "Organize your next steps"}<ArrowUpRight size={16}/></Link><p className="career-demo-note">Illustrative example · no real appointment or outcome implied.</p></div><ProductDisplay><div className="career-display-heading"><span>{section === "interview" ? <Quote size={15}/> : <CalendarClock size={15}/>}{section === "interview" ? "INTERVIEW STORY BUILDER" : "YOUR NEXT STEPS"}</span><span>DEMO</span></div>{section === "interview" ? <><div className="career-stars" role="group" aria-label="Interview story steps">{["Situation","Task","Action","Result"].map((s,i) => <button key={s} aria-pressed={step === i} onClick={() => setStep(i)}>{s}</button>)}</div><div className="career-story-answer" aria-live="polite"><p className="career-demo-label">{["THE CONTEXT","YOUR RESPONSIBILITY","WHAT YOU DID","WHAT CHANGED"][step]}</p><AnimatePresence mode="wait" initial={false}><motion.p key={step} className="career-story" initial={{opacity:0,y:reduced?0:6}} animate={{opacity:1,y:0}} exit={{opacity:0}} transition={{duration:reduced?0:.18}}>{stories[step]}</motion.p></AnimatePresence></div><div className="career-source-stamp"><span>Grounded in project evidence</span><Fingerprint size={17}/></div></> : <><div className="career-calendar-month"><span>YOUR WEEK, IN VIEW</span><b>September <i>14—18</i></b></div><div className="career-calendar-strip">{["MON","TUE","WED","THU","FRI"].map((day,i) => <div key={day} className={i === 2 ? "active" : ""}><small>{day}</small><b>{14+i}</b></div>)}</div><div className="career-proof-note"><Bell size={18}/><div><h3>Follow up with the hiring team</h3><p>Frontend Engineer · review your draft</p></div></div><div className="career-proof-note"><Quote size={18}/><div><h3>Prepare your project story</h3><p>Focus on one contribution you can explain clearly.</p></div></div><div className="career-display-footer"><span>Calendar changes need your review.</span><CheckCircle2 size={16}/></div></>}</ProductDisplay></div></section>;
}
