"use client";
import { useState } from "react";
import { api } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
export type EvidenceEntry = { id: string; title: string; statement: string; source: string; status: string; technologies?: string[]; details?: Record<string, string | number> };
export type StoryDocument = { id: string; kind?: string; title: string; subject: string; body: string; evidence: Array<{ quote: string; source: string }>; versions: Array<{ body: string; savedAt: string }> };
type Actions = { busy: boolean; run: (fn: () => Promise<void>) => Promise<void> };
const field = "w-full rounded-xl border bg-background p-3 text-sm focus-visible:outline-2 focus-visible:outline-violet-500";
const details = ["situation", "task", "action", "result", "project", "metrics", "dates"] as const;
export function EvidenceStudio({ evidence, busy, run, onDelete }: Actions & { evidence: EvidenceEntry[]; onDelete: (id: string) => void }) {
  const [editing, setEditing] = useState<EvidenceEntry | null>(null);
  return <div className="grid gap-6 lg:grid-cols-2"><Card className="space-y-4 p-6"><h2 className="text-xl font-semibold">{editing ? "Edit your evidence" : "Add real evidence"}</h2><p className="text-sm text-muted-foreground">Only confirm facts you can stand behind. Optional details help prepare interview stories. Editing evidence requires linked drafts to be reviewed again and cancels queued sends.</p>
    <form key={editing?.id ?? "new"} className="space-y-4" onSubmit={event => { event.preventDefault(); const form = event.currentTarget; const f = new FormData(form); void run(async () => {
      const body = { title: f.get("title"), statement: f.get("statement"), source: f.get("source"), status: f.get("status"), technologies: String(f.get("technologies")).split(",").map(s => s.trim()).filter(Boolean), details: { ...Object.fromEntries(details.filter(k => String(f.get(k)).trim()).map(k => [k, String(f.get(k)).trim()])), ...(f.get("teamSize") ? { teamSize: Number(f.get("teamSize")) } : {}) } };
      if (editing) await api.put(`/career/evidence/${editing.id}`, body); else await api.post("/career/evidence", body);
      form.reset(); setEditing(null);
    }); }}>
      <label className="block space-y-2 text-sm">Project or responsibility<input name="title" required minLength={2} maxLength={160} defaultValue={editing?.title} className={field} /></label>
      <label className="block space-y-2 text-sm">What did you do?<textarea name="statement" required minLength={10} maxLength={3000} rows={4} defaultValue={editing?.statement} className={field} /></label>
      <label className="block space-y-2 text-sm">Evidence source<input name="source" required minLength={2} maxLength={500} defaultValue={editing?.source} className={field} /></label>
      <label className="block space-y-2 text-sm">Technologies, separated by commas<input name="technologies" defaultValue={editing?.technologies?.join(", ")} className={field} /></label>
      <label className="block space-y-2 text-sm">Status<select name="status" defaultValue={editing?.status === "VERIFIED" ? "USER_CONFIRMED" : editing?.status ?? "USER_CONFIRMED"} className={field}><option value="USER_CONFIRMED">I confirm these facts</option><option value="INFERRED">Inferred — needs confirmation</option><option value="MISSING">Missing information</option></select></label>
      <details open={Boolean(editing)}><summary className="cursor-pointer text-sm font-medium">Project and interview details (optional)</summary><div className="mt-4 space-y-3">{details.map(key => <label key={key} className="block space-y-2 text-sm capitalize">{key}<textarea name={key} rows={2} maxLength={key === "dates" ? 100 : ["project", "metrics"].includes(key) ? 300 : 1000} defaultValue={editing?.details?.[key] ?? ""} className={field} /></label>)}<label className="block space-y-2 text-sm">Team size<input type="number" name="teamSize" min={1} step={1} defaultValue={editing?.details?.teamSize} className={field} /></label></div></details>
      <div className="flex gap-3"><Button disabled={busy}>Save evidence</Button>{editing && <Button type="button" variant="outline" disabled={busy} onClick={() => setEditing(null)}>Cancel edit</Button>}</div>
    </form></Card><Card className="space-y-4 p-6"><h2 className="text-xl font-semibold">Evidence bank</h2>{!evidence.length && <p>Start with one project or responsibility. Metrics are optional.</p>}{evidence.map(e => <article key={e.id} className="space-y-3 rounded-xl border p-4"><h3 className="font-medium">{e.title}</h3><p className="text-xs text-muted-foreground">{e.status.replaceAll("_", " ")}</p><p className="text-sm">{e.statement}</p><p className="text-xs text-muted-foreground">Source: {e.source}</p><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={busy} onClick={() => setEditing(e)}>Edit evidence</Button><Button variant="ghost" disabled={busy} onClick={() => void run(async () => { await api.delete(`/career/evidence/${e.id}`); if (editing?.id === e.id) setEditing(null); onDelete(e.id); })}>Delete evidence and linked drafts</Button></div></article>)}</Card></div>;
}
export function InterviewStudio({ evidence, documents, plan, busy, run }: Actions & { evidence: EvidenceEntry[]; documents: StoryDocument[]; plan: string }) {
  const [evidenceId, setEvidenceId] = useState("");
  const [story, setStory] = useState<StoryDocument | null>(null);
  return <div className="grid gap-6 lg:grid-cols-2"><Card className="space-y-4 p-6"><h2 className="text-xl font-semibold">Interview Story Builder</h2><p className="text-sm text-muted-foreground">Prepare a Situation, Task, Action and Result from confirmed evidence. Missing facts stay as questions. Update the evidence details before generating a more complete story.</p>{plan === "free" && <p className="rounded-xl border p-3 text-sm">Story generation is included with Pro and Career Plus. You can add project details to your Evidence Bank on any plan.</p>}<label className="block space-y-2 text-sm">Confirmed project<select className={field} value={evidenceId} onChange={e => setEvidenceId(e.target.value)}><option value="">Choose evidence</option>{evidence.filter(e => ["VERIFIED", "USER_CONFIRMED"].includes(e.status)).map(e => <option key={e.id} value={e.id}>{e.title}</option>)}</select></label><Button disabled={busy || !evidenceId || plan === "free"} onClick={() => void run(async () => setStory(await api.post<StoryDocument>("/career/stories", { evidenceId })))}>Build my story</Button><h3 className="font-medium">Saved stories</h3>{documents.filter(d => d.kind === "INTERVIEW_STORY").map(d => <button key={d.id} onClick={() => setStory(d)} className="block w-full rounded-xl border p-3 text-left text-sm">{d.title}</button>)}</Card>
    <Card className="space-y-4 p-6"><h2 className="text-xl font-semibold">Practice in your own words</h2>{!story ? <p className="text-sm text-muted-foreground">Create or open a story to review it here.</p> : <><label className="block space-y-2 text-sm">Your story<textarea rows={18} className={field} value={story.body} onChange={e => setStory({ ...story, body: e.target.value })} /></label><Button disabled={busy} onClick={() => void run(async () => setStory(await api.put<StoryDocument>(`/career/drafts/${story.id}`, { subject: story.subject, body: story.body, reviewed: true })))}>Save reviewed story</Button><details><summary className="cursor-pointer">Sources and previous edits</summary>{story.evidence.map((c, i) => <blockquote key={i} className="mt-3 border-l-2 pl-3 text-sm">{c.quote}<cite className="block text-muted-foreground">{c.source}</cite></blockquote>)}{story.versions.map((v, i) => <p key={i} className="mt-3 whitespace-pre-wrap border-t pt-3 text-sm">{v.body}</p>)}</details><Button variant="ghost" disabled={busy} onClick={() => void run(async () => { await api.delete(`/career/drafts/${story.id}`); setStory(null); })}>Delete story</Button></>}</Card></div>;
}

export type DiscoveryPreferences = { roles?: string[]; locations?: string[]; industries?: string[]; workplace?: string; salaryMin?: number | null; salaryCurrency?: string | null; writingStyle?: { tone: string; length: string } };
export function PreferencesForm({ preferences, busy, run }: Actions & { preferences?: DiscoveryPreferences }) {
  return <form key={JSON.stringify(preferences)} className="grid gap-3 sm:grid-cols-2" onSubmit={event => { event.preventDefault(); const f = new FormData(event.currentTarget); void run(async () => { await api.put("/career/preferences", { roles: String(f.get("roles")).split(",").map(s => s.trim()).filter(Boolean), locations: String(f.get("locations")).split(",").map(s => s.trim()).filter(Boolean), industries: String(f.get("industries")).split(",").map(s => s.trim()).filter(Boolean), workplace: f.get("workplace"), salaryMin: f.get("salaryMin") ? Number(f.get("salaryMin")) : null, salaryCurrency: f.get("salaryCurrency") ? String(f.get("salaryCurrency")).toUpperCase() : null }); }); }}>
    {(["roles", "locations", "industries"] as const).map(key => <label key={key} className="block space-y-2 text-sm capitalize">{key} (comma separated)<input name={key} defaultValue={preferences?.[key]?.join(", ")} className={field} /></label>)}
    <label className="block space-y-2 text-sm">Workplace<select name="workplace" defaultValue={preferences?.workplace ?? "ANY"} className={field}>{["ANY", "REMOTE", "HYBRID", "ON_SITE"].map(w => <option key={w}>{w}</option>)}</select></label>
    <label className="block space-y-2 text-sm">Minimum annual salary (optional)<input type="number" min={0} name="salaryMin" defaultValue={preferences?.salaryMin ?? ""} className={field} /></label>
    <label className="block space-y-2 text-sm">Currency code (optional)<input name="salaryCurrency" pattern="[A-Za-z]{3}" minLength={3} maxLength={3} placeholder="USD" defaultValue={preferences?.salaryCurrency ?? ""} className={field} /></label>
    <p className="text-xs text-muted-foreground sm:col-span-2">Salary and industry preferences are saved for review. Sources without these details cannot establish a match.</p><Button disabled={busy}>Save preferences</Button>
  </form>;
}
